"""
Django settings for reviewlo_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_environment():
    """Load a local, git-ignored .env file without adding a runtime dependency."""
    environment_file = BASE_DIR / ".env"
    if not environment_file.exists():
        return

    for raw_line in environment_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        os.environ.setdefault(name.strip(), value.strip().strip('"').strip("'"))


load_local_environment()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Fail-safe default: DEBUG is OFF unless explicitly turned on. A missing
# environment variable must never silently enable debug mode in production.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

# Known-compromised placeholder values that must never be used as a real
# signing key, even if someone pastes one of them into an environment
# variable by mistake (e.g. copying an old/leaked value).
_KNOWN_INSECURE_SECRET_KEYS = {
    "django-insecure-local-development-only",
}


def _resolve_secret_key():
    configured = os.environ.get("DJANGO_SECRET_KEY")

    if configured:
        if configured in _KNOWN_INSECURE_SECRET_KEYS:
            raise ImproperlyConfigured(
                "DJANGO_SECRET_KEY is set to a known-insecure placeholder value. "
                "Generate a new secret and set it via the DJANGO_SECRET_KEY environment variable."
            )
        return configured

    if DEBUG:
        # Local-development-only: generate a fresh random key for this process.
        # It is never persisted and never reused, so it can never become a
        # known/guessable production signing key. Set DJANGO_SECRET_KEY in a
        # local .env file (git-ignored) if you want it to stay stable across
        # dev server restarts.
        from django.core.management.utils import get_random_secret_key
        return get_random_secret_key()

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set via environment variable when DJANGO_DEBUG is not true."
    )


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _resolve_secret_key()

def comma_separated_environment(name, default=""):
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


ALLOWED_HOSTS = comma_separated_environment(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,reviewlog.onrender.com,reviewlog.vercel.app,reviewlog-2lafwjpe0-eshal-s-projects2.vercel.app",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'rest_framework',
    'reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reviews.middleware.NoStoreApiCacheMiddleware',
]

ROOT_URLCONF = 'reviewlog_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reviewlog_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

CORS_ALLOWED_ORIGINS = comma_separated_environment(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,https://reviewlog.vercel.app,https://reviewlog-2lafwjpe0-eshal-s-projects2.vercel.app",
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "false").lower() == "true"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "false").lower() == "true"

# The deployed frontend origin, used to build links (e.g. password reset)
# that are sent in emails and must point at the SPA, not the API.
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://reviewlog.vercel.app")

# Email delivery for password resets etc. Defaults to printing to the
# console (safe for local dev). Set EMAIL_BACKEND to a real SMTP/provider
# backend (e.g. django.core.mail.backends.smtp.EmailBackend, or
# django-anymail for SendGrid/Mailgun/SES) via environment variables in
# production, or reset emails will only appear in the Render logs.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@reviewlog.app")
