# Generated by Django 6.0.6 on 2026-07-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie')], max_length=10)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
