# Generated by Django 6.0.6 on 2026-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
